[package]
name = "kap"
description = "A dead simple library to sequence keystrokes"
version = "0.0.0"
edition = "2021"


[dependencies]
tokio = { version = "1.16.1", features = ["rt-multi-thread", "time", "macros"] }
device_query = "1.1.1"
